apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
  labels:
    env: prod
    app: main
    tier: backend
    owner: alex
spec:
  selector:
    matchLabels:
      project: gateway  #service with look for those PODS Labels
  template:
    metadata:
      labels:
        project: gateway
    spec:
      automountServiceAccountToken: true
      containers:
        - name: service-gateway
          image: nelson9291/gateway-test:1.0
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-gateway
  maxReplicas: 6
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-gateway
  labels:
    env: prod
spec:
  selector:
    project: gateway  #selecting PODS with those Labels
  ports:
    - name: app-gateway
      protocol: TCP
      port: 8080 #port loadBalancer
      targetPort: 8080 #port pod
  type: LoadBalancer

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-gateway
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-gateway
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: service-gateway
  apiGroup: ""