apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric8-admin
  namespace: devops-platform
rules:
  # Just an example, feel free to change it
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: fabric8-admin
  apiGroup: rbac.authorization.k8s.io