apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-friend
  labels:
    env: prod
    app: main
    tier: backend
    owner: alex
spec:
  selector:
    matchLabels:
      project: friends  #service with look for those PODS Labels
  template:
    metadata:
      labels:
        project: friends
    spec:
      containers:
        - name: service-friend
          image: nelson9291/service-friend:1.1
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres-db-lb:5432/test_db

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-friend
  maxReplicas: 6
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-friend
  labels:
    env: prod
spec:
  selector:
    project: friends  #selecting PODS with those Labels
  ports:
    - name: app-friend
      protocol: TCP
      port: 8081 #port loadBalancer
      targetPort: 8081 #port pod

