server:
  port: 8081


spring:
  application:
    name: service-friend
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL}
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

